# ~/.config/i3blocks/config
# Orden de los bloques (de izquierda a derecha)
separator_block_width=15
separator=true

order += ethernet
order += disk
order += cpu_temp
order += memory
order += time


[ethernet]
command=ip -o -4 route show default | awk '{print $5 " " $9}' | head -1 || echo "down"
interval=10
color=#00ff00

[disk]
command=~/.config/i3/Scripts/My-scripts/Disk.sh
interval=10
color=#7b68ee


[update]
command=~/.config/i3/Scripts/My-scripts/Upadate.sh
interval= 30


[cpu_temp]
command=sensors k10temp-pci-00c3 | awk '/Tctl:/ {print $2}' || echo "??°C"
interval=5
color=#00ff00

[ssh]
command=~/.config/i3/Scripts/My-scripts/ssh.sh
interval=30
markup=pango


[memory]
command=/home/Anchovy/.config/i3/Scripts/memory
interval=30
color=#ffff00

[time]
command=date '+%Y-%m-%d %H:%M:%S'
interval=1
color=#ffffff

