[FileDialog]
history=file:///home/Anchovy/CVs, file:///home/Anchovy/Courses-P/Modern_C/IMG, file:///home/Anchovy, file:///home/Anchovy/Downloads, file:///home/Anchovy/Mega_Shit_Folder/Books
lastVisited=file:///home/Anchovy/Downloads
qtVersion=6.10.1
shortcuts=file:///home/Anchovy, file:
sidebarWidth=114
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xd1\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xf5\0\0\0\x1\0\0\0\0\0\0\0\x39\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0\x66\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1)"
viewMode=Detail
