# Prefix más cómodo (Ctrl-a en lugar de Ctrl-b)
unbind C-b
set -g prefix C-f
bind C-f send-prefix

# Reload config
bind r source-file /home/Anchovy/.config/tmux/tmux.conf  \; display "Tmux is pwd"

# Mejor manejo de ventanas y paneles
bind | split-window -h
bind - split-window -v
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind y kill-pane
bind c new-window

bind n next-window
bind m previous-window
#rename-window
bind-key R command-prompt -I "#W" "rename-window '%%'"

# Barra de estado moderna
set -g status-justify left
set -g status-interval 2
setw -g window-status-current-format " #[fg=#dc322f]#I:#W#[default] "
set -g status-left ''

set -g status-position bottom
set -g status-style "bg=black"
set -g status-left '#[fg=color14,bold]#S '
set -g status-right '  #[fg=color250] %Y-%m-%d #[fg=white,bold]%H:%M:%S'

set -g status-right-length 50
set -g status-left-length 20
# Muestra hora y fech
set -g mouse on

# Usa colores 256
set -g default-terminal "screen-256color"

# Tiempo de escape más corto para mayor velocidad
set -s escape-time 0

# Activar movimientos tipo Vim en copy-mode
setw -g mode-keys vi

# Scroll con Shift + PageUp
bind -T copy-mode-vi PageUp send-keys -X page-up

# Copiar con 'y' al portapapeles usando xclip
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard -in"

# Plugin manager
# List of plugins
# En tu status-right (añádelo manualmente en tmux.conf)
# #(while true; do if [ -f "$TIMER_STATE_FILE" ]; then start=$(cat "$TIMER_STATE_FILE"); now=$(date +%s); elapsed=$((now - start)); printf "⏱️ %02d:%02d " $((elapsed/60)) $((elapsed%60)); else echo ""; fi; sleep 1; done) &
set -g @plugin 'tmux-plugins/tpmset -g @plugin 'ayzenquwe/tmux-ping'
set -g @plugin 'olimorris/tmux-pomodoro-plus'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '/home/Anchovy/.config/tmux/plugins/tpm/tpm'
